name: flutter_graphql_jobs
description: Example of a Flutter project using GraphQL to fetch jobs from the GraphQL API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  bloc: ^8.0.3
  build_runner: ^2.1.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10+2
  graphql: ^5.1.1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  connectivity_plus: ^2.3.5


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
