name: flutter_graphql_jobs
description: Example of a Flutter project using GraphQL to fetch jobs from the GraphQL API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  bloc: ^8.0.3
  build_runner: ^2.1.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10+2
  graphql: ^5.1.1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  connectivity_plus: ^2.3.5
  splash_screen_view: ^3.0.0


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/img-1.png


splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.
  color: '#A862EA'
  # background_image: "assets/icon/logo_app.png"
  # Optional parameters are listed below.
#  image: assets/img-1.png
  color_dark: "#A862EA"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # android: true
  # ios: true
  #web: false
#   android_gravity: center
#   ios_content_mode: center
  #web_image_mode: center
  # fullscreen: true
  info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
