name: flutter_graphql_jobs
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.18.0 <3.0.0"
    flutter: 3.3.0

dependencies:
    bloc: ^8.1.0
    build_runner: ^2.1.8
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.1
    flutter_markdown: ^0.6.9+1
    graphql: ^5.1.2-beta.4
    json_annotation: ^4.4.0
    json_serializable: ^6.1.5

dev_dependencies:
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
